server:
  port: 8083
  servlet:
    context-path: /informacoes-cadastrais

# Configuration postgresql Database
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.247.224.100:3306/informacoes_cadastrais_db
    username: root
    password: vfbf5ylolHFgi474
    initial-size: 2
    max-active: 5
    max-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect