apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulo-informacoes-cadastrais
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modulo-informacoes-cadastrais
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: modulo-informacoes-cadastrais
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: rafaelcanejo/modulo-informacoes-cadastrais:1.0.0
          imagePullPolicy: Always
          name: modulo-informacoes-cadastrais
          ports:
            
            - containerPort: 8083
              name: 8083tcp
              protocol: TCP
            
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
